name: Build docker image

on:
  push:
    branches: [ main ]
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
  pull_request:
    branches: [ main ]

jobs:
  build_types:
    name: Build server
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/redis-fetch-server
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{raw}}
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build server
        uses: docker/build-push-action@v3
        with:
          # push: ${{ startsWith(github.event.ref, 'refs/tags/v') }}
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          cache-from: type=gha,scope=main
          cache-to: type=gha,mode=max,scope=main
